name: Run Nifty 100 Screener

on:

  workflow_dispatch:

jobs:

  run-python:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'


      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Python Script
        run: |
          python nifty_screener.py


      - name: Check Files
        run: |
          echo "Current Directory:"
          pwd

          echo "Files:"
          ls -la


      - name: Upload HTML Report
        uses: actions/upload-artifact@v4

        with:
          name: nifty100-html-report
          path: nifty100_20day_high.html
          if-no-files-found: error
